name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'  # Yarn-specific caching

      # Install Yarn if not using v3+ with zero-installs
      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile  # Yarn equivalent of "npm ci"

      - name: Run tests
        run: yarn test  # Your test script from package.json